FROM node:16.17.1-alpine
WORKDIR /wander

RUN mkdir -p /wander/web
RUN mkdir -p /wander/shared

RUN npm install -g pnpm && pnpm config set store-dir /root/.local/share/pnpm/store/v3

COPY ./web/pnpm-lock.yaml /wander/web
RUN cd web && pnpm fetch
COPY ./web /wander/web
COPY ./shared /wander/shared
RUN cd web && pnpm install --offline

WORKDIR /wander/web
CMD [ "pnpm", "run", "dev" ]